# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Alternative Name', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Normalized name', max_length=250)),
                ('geonames_id', models.CharField(blank=True, help_text='GND-ID', max_length=50)),
                ('lat', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('alternative_name', models.ManyToManyField(blank=True, help_text='Alternative names', max_length=250, to='places.AlternativeName')),
                ('part_of', models.ForeignKey(blank=True, help_text='A place (country) this place is part of.', null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
            ],
        ),
    ]
