# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.CharField(blank=True, choices=[('address', 'address'), ('city', 'city'), ('country', 'country')], max_length=50, null=True),
        ),
    ]
