# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='part_of',
            field=models.ForeignKey(blank=True, help_text='A place (country) this place is part of.', null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, help_text='Normalized name', max_length=250),
        ),
    ]
