# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_place_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(blank=True, choices=[('city', 'city'), ('country', 'country')], max_length=50, null=True),
        ),
    ]
