# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20160530_1207'),
        ('places', '0002_auto_20160512_1510'),
    ]

    operations = [
    ]
