# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='open_source',
            field=models.CharField(blank=True, choices=[('', 'No information provided.'), ('0', 'Proprietary, all material is copyrighted. The ‘source’ is closed and not reusable by other research projects. To access the material, users must pay a subscription.'), ('0.5', 'Same as above, but the subscription is free of charge.'), ('1', 'Open Access. The texts may be accessed through specific software, but the source is not accessible.'), ('1.5', ' Open Access and Open Source. All data underlying the digital edition is freely available for access, study, redistribution and improvement (reuse)')], max_length=255, verbose_name='Open Source/Open Access'),
        ),
    ]
