# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='edition',
            name='begin_date',
            field=models.DateField(blank=True, help_text='Year the project started.', null=True),
        ),
        migrations.AlterField(
            model_name='edition',
            name='cc_license',
            field=models.NullBooleanField(help_text='The values 1 or 0 are used to specify if the project is protected by a Creative Commons License.', verbose_name='Creative Commons License'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='download',
            field=models.CharField(blank=True, choices=[('0', 'no'), ('0.5', 'partially'), ('1', 'yes')], help_text='The XML-TEI encoded text is available for download.', max_length=255, null=True, verbose_name='XML-TEI transcription to download'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='end_date',
            field=models.DateField(blank=True, help_text='Year the project ended. If ongoing, leave blank.', null=True),
        ),
        migrations.AlterField(
            model_name='edition',
            name='key_or_ocr',
            field=models.CharField(blank=True, choices=[('Keyed', 'Keyed'), ('OCR', 'OCR')], help_text='The source text was digitised with Optical Character Recognition (OCR) software or manually keyed in.', max_length=12, verbose_name='OCR or keyed?'),
        ),
        migrations.RemoveField(
            model_name='edition',
            name='language',
        ),
        migrations.AlterField(
            model_name='edition',
            name='open_source',
            field=models.CharField(blank=True, choices=[('0', 'Proprietary, all material is copyrighted. The ‘source’ is closed and not reusable by other research projects. To access the material, users must pay a subscription.'), ('0.5', 'Same as above, but the subscription is free of charge.'), ('1', 'Open Access. The texts may be accessed through specific software, but the source is not accessible.'), ('1.5', ' Open Access and Open Source. All data underlying the digital edition is freely available for access, study, redistribution and improvement (reuse)')], max_length=255, verbose_name='Open Source/Open Access'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='search',
            field=models.NullBooleanField(help_text='The values 1 or 0 are used to tell us if the edition provides string matching search possibilities.', verbose_name='String matching search'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='source_translation',
            field=models.CharField(blank=True, help_text='The project provides a translation of the source text. If so, the corresponding three-letter ISO code should be used. If not, type 0.', max_length=3, verbose_name='Source text translation'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='tei_transcription',
            field=models.CharField(blank=True, choices=[('0', 'XML not used'), ('0.5', 'XML but not TEI'), ('1', 'XML-TEI is used')], help_text='The source text is encoded in XML-TEI.', max_length=255, null=True, verbose_name='XML-TEI transcription'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='text_image',
            field=models.NullBooleanField(help_text='The transcription and the image are linked so that clicking on a word in the image brings up the corresponding textual token and viceversa.', verbose_name='Text-image linking'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='textual_variance',
            field=models.CharField(blank=True, choices=[('0', 'No account of textual variance is given. The digital edition is a reproduction of a given print edition without any account of variants.'), ('0.5', 'The digital edition is a reproduction of a given print scholarly edition and reproduces the selected textual variants extant in the apparatus criticus of that edition, or: the edition does not follow a digital paradigm, in that the variants are not automatically computable the way they are encoded.'), ('1', "This edition is 'based on full-text transcription of original texts into electronic form'.")], max_length=255, verbose_name='Account of textual variance'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='value_witnesses',
            field=models.CharField(blank=True, choices=[('N/A', 'Not applicable, as no information about the source of the text is given, though it is easily assumable that the source is another digital edition or a printed edition (possibly even a scholarly edition'), ('0', 'The only witness modelled digitally is a printed non-scholarly edition, used as a source for the digital edition.'), ('0.5', 'Same as above, but the witness/source is a scholarly edition.'), ('1', 'The witnesses are traditional philological primary sources (including manuscripts, inscriptions or papyri)')], max_length=255, null=True, verbose_name='Value of witnesses'),
        ),
        migrations.RemoveField(
            model_name='edition',
            name='website_language',
        ),
        migrations.AddField(
            model_name='edition',
            name='language',
            field=models.ManyToManyField(blank=True, help_text='The language(s) of the source text. Three-letter ISO Codes are used.', related_name='lang_source', to='editions.Language'),
        ),
        migrations.AddField(
            model_name='edition',
            name='website_language',
            field=models.ManyToManyField(blank=True, help_text='The language the project website is written in. Three-letter ISO Codes should be used.', max_length=3, related_name='lang_website', to='editions.Language'),
        ),
    ]
