# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0004_auto_20160530_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='advanced_search',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('no information provided', 'no information provided')], help_text='The values 1 or 0 are used to tell us if the edition provides an advanced search functionality.', max_length=40),
        ),
        migrations.AlterField(
            model_name='edition',
            name='cc_license',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('no information provided', 'no information provided')], help_text='The values 1 or 0 are used to specify if the project is protected by a Creative Commons License.', max_length=40, verbose_name='Creative Commons License'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='digital',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('no information provided', 'no information provided')], help_text='A digital edition can not be converted to a printed edition without substantial loss of content or functionality - vice versa: a retrodigitized printed edition is not a Scholarly Digital Edition (but it may evolve into a Scholarly Digital Edition through new content or functionalities)', max_length=40),
        ),
        migrations.AlterField(
            model_name='edition',
            name='edition',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('no information provided', 'no information provided')], help_text='An edition must represent its material (usually as transcribed/edited text) - a catalog, an index, a descriptive database is not an edition.', max_length=40),
        ),
        migrations.AlterField(
            model_name='edition',
            name='glossary',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('no information provided', 'no information provided')], help_text='The values 1 or 0 are used to tell us if the edition provides a glossary.', max_length=40),
        ),
        migrations.AlterField(
            model_name='edition',
            name='image_manipulation',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('no information provided', 'no information provided')], help_text='The values 1 and 0 are used to tell us whether the user can manipulate these images in any way within the edition (brightness, saturation, etc.).', max_length=40),
        ),
        migrations.AlterField(
            model_name='edition',
            name='images',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('no information provided', 'no information provided')], help_text='The values 1 or 0 are used to tell us if the edition comes with images.', max_length=40),
        ),
        migrations.AlterField(
            model_name='edition',
            name='indices',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('no information provided', 'no information provided')], help_text='The values 1 or 0 are used to tell us if the edition provides indices.', max_length=40),
        ),
        migrations.AlterField(
            model_name='edition',
            name='print_friendly',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('no information provided', 'no information provided')], help_text='The values 1 or 0 are used to tell if the project provides a print-friendly view of the text (e.g. PDF).', max_length=40),
        ),
        migrations.AlterField(
            model_name='edition',
            name='prototype',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('no information provided', 'no information provided')], help_text='A Scholarly Digital Edition (SDE) is a publication of the material in question; a SDE project is not the same as a SDE, that means a SDE is more than a plan or a prototype.', max_length=40),
        ),
        migrations.AlterField(
            model_name='edition',
            name='scholarly',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('no information provided', 'no information provided')], help_text='An edition must be critical, must have critical components - a pure facsimile is not an edition, a digital library is not an edition.', max_length=40),
        ),
        migrations.AlterField(
            model_name='edition',
            name='search',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('no information provided', 'no information provided')], help_text='The values 1 or 0 are used to tell us if the edition provides string matching search possibilities.', max_length=40, verbose_name='String matching search'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='text_image',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('no information provided', 'no information provided')], help_text='The transcription and the image are linked so that clicking on a word in the image brings up the corresponding textual token and viceversa.', max_length=40, verbose_name='Text-image linking'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='zoom_images',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('no information provided', 'no information provided')], help_text='The values 1 or 0 are used to tell us if the user can zoom in or out of images within the edition.', max_length=40),
        ),
    ]
