# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0006_auto_20160530_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='download',
            field=models.CharField(blank=True, choices=[('no information provided', 'no information provided'), ('0', 'no'), ('0.5', 'partially'), ('1', 'yes')], help_text='The XML-TEI encoded text is available for download.', max_length=255, null=True, verbose_name='XML-TEI transcription to download'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='open_source',
            field=models.CharField(blank=True, choices=[('no information provided', 'no information provided'), ('0', 'Proprietary, all material is copyrighted. The ‘source’ is closed and not reusable by other research projects. To access the material, users must pay a subscription.'), ('0.5', 'Same as above, but the subscription is free of charge.'), ('1', 'Open Access. The texts may be accessed through specific software, but the source is not accessible.'), ('1.5', ' Open Access and Open Source. All data underlying the digital edition is freely available for access, study, redistribution and improvement (reuse)')], help_text='something', max_length=255, verbose_name='Open Source/Open Access'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='tei_transcription',
            field=models.CharField(blank=True, choices=[('no information provided', 'no information provided'), ('0', 'XML not used'), ('0.5', 'XML but not TEI'), ('1', 'XML-TEI is used')], help_text='The source text is encoded in XML-TEI.', max_length=255, null=True, verbose_name='XML-TEI transcription'),
        ),
    ]
